 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/macrossx-exam?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
  jpa:
    show-sql: true
  http:
    encoding:
      charset: UTF-8 
      enabled: true
      force: true
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
server:
  port: 81 
  servlet:
    context-path: "/exam"