/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.x19990416.macrossx.exam.backend;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
		
@SpringBootApplication
@ComponentScan(basePackages={"com.github.x19990416.macrossx.exam"})
@EnableJpaRepositories("com.github.x19990416.macrossx.exam.data.repository")
@EntityScan("com.github.x19990416.macrossx.exam.data.persistence")  
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}